name: Pull Request Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  quality-gates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper diff analysis
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting with error output
        run: npm run lint

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: TypeScript compilation check
        run: npx tsc --noEmit

      - name: Build project
        run: npm run build

      - name: Check for TODO/FIXME comments
        run: |
          if grep -r "TODO\|FIXME" src/ --include="*.ts" --include="*.js"; then
            echo "❌ Found TODO/FIXME comments that should be addressed"
            exit 1
          else
            echo "✅ No TODO/FIXME comments found"
          fi

      - name: Check documentation links
        run: |
          BROKEN_LINKS_OUTPUT=$(npm run docs:validate:links 2>&1)
          NON_API_BROKEN_LINKS=$(echo "$BROKEN_LINKS_OUTPUT" | grep -v "/api-reference/" || true)
          
          if echo "$NON_API_BROKEN_LINKS" | grep -q " ⎿ "; then
            echo "❌ Non-API reference broken links detected!"
            echo "Please fix these broken links (excluding known API reference false positives):"
            echo "$NON_API_BROKEN_LINKS"
            exit 1
          fi
          
          API_FALSE_POSITIVES=$(echo "$BROKEN_LINKS_OUTPUT" | grep -c "/api-reference/" || echo "0")
          if [ "$API_FALSE_POSITIVES" -gt 0 ]; then
            echo "ℹ️  Note: $API_FALSE_POSITIVES API reference links flagged as broken (likely false positives)"
          fi
          
          echo "✅ Documentation links validated successfully"

  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for vulnerabilities
        run: npm audit --audit-level=moderate

      - name: Check for outdated packages
        run: npm outdated || true
